version: '3.8'
networks:
  dnsnetwork:
    ipam:
      driver: default
      config:
        - subnet: "10.8.8.0/24"
    
services:
  dnsmasq:
    restart: always
    image: dnsmasq:2022.03.22
    hostname: dnsmasq
    environment:
      - "PS1=🐳 \\e[1;36m[$$(date '+%F %T %a %Z')] \\e[1;33m\\u\\e[m@\\e[1;32m\\h:\\e[1;33m\\w\\e[m\\ $$ "
      - "TZ=Asia/Singapore"
      - "HTTP_USER=foo"
      - "HTTP_PASS=bar"
    networks:
      dnsnetwork:
        ipv4_address: 10.8.8.3
    tty: true
    volumes:
#     - ./etc/dnsmasq.d/adservers.conf:/etc/dnsmasq.d/adservers.conf
      - ./etc/dnsmasq.d/dnsmasq.conf:/etc/dnsmasq.d/dnsmasq.conf
    ports:
      - "53:53/udp"
      - "53:53"
      - "5380:8080"
    links:
      - "dnscrypt"
    cap_add:
      - NET_ADMIN

  dnscrypt:
    restart: always
    image: dnscrypt:2021.8.29
    hostname: dnscrypt
    environment:
      - "PS1=🐳 \\e[1;36m[$$(date '+%F %T %a %Z')] \\e[1;33m\\u\\e[m@\\e[1;32m\\h:\\e[1;33m\\w\\e[m\\ $$ "
    networks:
      dnsnetwork:
        ipv4_address: 10.8.8.2
    tty: true
    volumes:
      - ./etc/dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml
#   ports:
#     - "${MY_DOCKER_IP:-127.0.0.1}:53000:53/udp"
#     - "${MY_DOCKER_IP:-127.0.0.1}:53000:53"
#   cap_add:
#     - NET_ADMIN
#   command: ["tail", "-f", "/dev/null"]

# Visit http://<docker-host>:5380, authenticate with foo/bar and you should see
# http://foo:bar@localhost:5380
# docker-compose -f docker-compose.yml up
